# Generated by Django 3.0.3 on 2020-02-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('primerApellido', models.CharField(max_length=60, verbose_name='Apellido paterno')),
                ('segundoApellido', models.CharField(blank=True, max_length=60, null=True, verbose_name='Apellido materno')),
                ('numero_ss', models.CharField(max_length=20, verbose_name='Número de Seguro Social')),
                ('fecha_nac', models.DateField(verbose_name='Fecha de nacimiento')),
                ('tipo_sangre', models.CharField(choices=[('A+', 'A positivo'), ('A-', 'A negativo'), ('O+', 'O positivo')], max_length=3, verbose_name='Tipo de sangre')),
            ],
        ),
    ]
