# Generated by Django 3.0.4 on 2020-05-07 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Categoría')),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=30, verbose_name='Clave')),
                ('nombre', models.CharField(max_length=150, verbose_name='Artículo')),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Descripción')),
                ('imgen', models.ImageField(upload_to='articulos', verbose_name='Imágen')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Precio unitario')),
                ('stock', models.IntegerField(verbose_name='Unidades')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='articulos.Categoria', verbose_name='Categoría')),
            ],
        ),
    ]
